apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: v11
  template:
    metadata:
      labels:
        app: vote-bot
        version: v11
    spec:
      imagePullSecrets:
      - name: test-reg1
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivoto:80
        - name: DEPLOYED_REGION
          value: "NYC"
        - name: TTL
          value: "60"
        image: ysharma859/emojivoto-web:v13
        # imagePullPolicy: Always
        name: vote-bot
        resources:
          requests:
            cpu: 10m
